<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <UserSecretsId>0932819b-23f1-4ae8-b2c5-813cd3eb6baa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\MyFeature\**" />
    <Content Remove="Areas\MyFeature\**" />
    <EmbeddedResource Remove="Areas\MyFeature\**" />
    <None Remove="Areas\MyFeature\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tHerdBackend.Share\tHerdBackend.Infra\tHerdBackend.Infra.csproj" />
    <ProjectReference Include="..\..\tHerdBackend.Share\tHerdBackend.Services\tHerdBackend.Services.csproj" />
    <ProjectReference Include="..\..\tHerdBackend.StyleMain\tHerdBackend.UIKit.Rcl\tHerdBackend.UIKit.Rcl.csproj" />
  </ItemGroup>



</Project>
