<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <UserSecretsId>8b08e92c-9920-4beb-a92c-c346fed309dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\CNT\Controllers\NewFolder\**" />
    <Content Remove="Areas\CNT\Controllers\NewFolder\**" />
    <EmbeddedResource Remove="Areas\CNT\Controllers\NewFolder\**" />
    <None Remove="Areas\CNT\Controllers\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="bundleconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bundleconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="X.PagedList" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tHerdBackend.Share\tHerdBackend.Services\tHerdBackend.Services.csproj" />
    <ProjectReference Include="..\..\tHerdBackend.StyleMain\tHerdBackend.UIKit.Rcl\tHerdBackend.UIKit.Rcl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\js\tinymce-setup.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>



</Project>
