<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <UserSecretsId>4cd2016e-44c0-4857-9c85-5a4427bf6f17</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="bundleconfig.json" />
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bundleconfig.json" />
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tHerdBackend.Share\tHerdBackend.Infra\tHerdBackend.Infra.csproj" />
    <ProjectReference Include="..\..\tHerdBackend.Share\tHerdBackend.Services\tHerdBackend.Services.csproj" />
  </ItemGroup>
</Project>
